# Notebook for testing and playing with TrajectoryDistances

In [1]:
import sbmlcore
import pandas as pd

In [2]:
b = {'segid': ['A', 'A', 'A', 'B', 'C', 'C'], 'mutation': ['I3D','S4K', 'Q5V', 'R6D', 'S450F', 'D435F']} #N.B. Mutation must include offset
df = pd.DataFrame.from_dict(b)
df.columns

Index(['segid', 'mutation'], dtype='object')

In [3]:
a = sbmlcore.TrajectoryDistances(
        "./tests/rpob-5uh6-3-warm.gro.gz",
        [
            "./tests/rpob-5uh6-3-md-1-50ns-dt10ns-nojump.xtc",
            "./tests/rpob-5uh6-3-md-2-50ns-dt10ns-nojump.xtc",
        ],
        "./tests/5uh6.pdb",
        "resname RFP",
        "max RFP",
        distance_type="max",
        offsets = {'A': 0, 'B': 0, 'C': -6},
        percentile_exclusion=True,
    )
a.return_dist_df()

     segid  resid    max RFP amino_acid
0        A      3  72.000161          I
1        A      4  71.859083          S
2        A      5  75.431009          Q
3        A      6  74.446025          R
4        A      7  71.537496          P
...    ...    ...        ...        ...
3238     F    524  54.412016          R
3239     F    525  50.833875          D
3240     F    526  50.095013          Y
3241     F    527  49.678343          L
3242     F    528  46.477291          D

[3243 rows x 4 columns]

In [4]:
df = a.add_feature(df)
df

In [6]:
t = sbmlcore.TrajectoryDistances(
        "./tests/rpob-5uh6-3-warm.gro.gz",
        [
            "./tests/rpob-5uh6-3-md-1-50ns-dt10ns-nojump.xtc",
            "./tests/rpob-5uh6-3-md-2-50ns-dt10ns-nojump.xtc",
        ],
        "./tests/5uh6.pdb",
        "resname RFP",
        "mean RFP",
        distance_type="mean",
        offsets = {'A': 0, 'B': 0, 'C': -6},
        percentile_exclusion=True,
    )
t.return_dist_df()

     segid  resid   mean RFP amino_acid
0        A      3  70.661801          I
1        A      4  71.364778          S
2        A      5  74.491729          Q
3        A      6  73.099193          R
4        A      7  70.858813          P
...    ...    ...        ...        ...
3238     F    524  52.316929          R
3239     F    525  49.195076          D
3240     F    526  48.442292          Y
3241     F    527  47.819681          L
3242     F    528  45.088313          D

[3243 rows x 4 columns]

In [7]:
df = t.add_feature(df)
df

In [9]:
p = sbmlcore.TrajectoryDistances(
        "./tests/rpob-5uh6-3-warm.gro.gz",
        [
            "./tests/rpob-5uh6-3-md-1-50ns-dt10ns-nojump.xtc",
            "./tests/rpob-5uh6-3-md-2-50ns-dt10ns-nojump.xtc",
        ],
        "./tests/5uh6.pdb",
        "resname RFP",
        "median RFP",
        distance_type="median",
        offsets = {'A': 0, 'B': 0, 'C': -6},
        percentile_exclusion=True,
    )
df = p.add_feature(df)
df

  segid  resid mutation    max RFP   mean RFP  median RFP
0     A      3      I3D  72.000161  70.661801   70.783703
1     A      4      S4K  71.859083  71.364778   71.525979
2     A      5      Q5V  75.431009  74.491729   74.457994
3     B      6      R6D  54.469711  52.361124   51.797465
4     C    450    S450F  13.887488  12.229636   11.714328
5     C    435    D435F   9.464016   8.713272    9.211318

In [10]:
p = sbmlcore.TrajectoryDistances(
        "./tests/rpob-5uh6-3-warm.gro.gz",
        [
            "./tests/rpob-5uh6-3-md-1-50ns-dt10ns-nojump.xtc",
            "./tests/rpob-5uh6-3-md-2-50ns-dt10ns-nojump.xtc",
        ],
        "./tests/5uh6.pdb",
        "resname RFP",
        "min RFP",
        distance_type="min",
        offsets = {'A': 0, 'B': 0, 'C': -6},
        percentile_exclusion=True,
    )
df = p.add_feature(df)
df

  segid  resid mutation    max RFP   mean RFP  median RFP    min RFP
0     A      3      I3D  72.000161  70.661801   70.783703  69.617708
1     A      4      S4K  71.859083  71.364778   71.525979  70.495139
2     A      5      Q5V  75.431009  74.491729   74.457994  73.682515
3     B      6      R6D  54.469711  52.361124   51.797465  51.712725
4     C    450    S450F  13.887488  12.229636   11.714328  11.534613
5     C    435    D435F   9.464016   8.713272    9.211318   6.590122